version: '3.7'
    
services:
    web:
        image: omarelsheekh.azurecr.io/dockerexample
        build: .
        command: python manage.py runserver 0.0.0.0:3000
        ports:
            - "3000:3000"
